Занятие 1: Основы JavaScript
js-tasks-ru/jsbasic-20210225_natalya72 pull request #2
Opened 2021-03-05 15:23 UTC by nataliaKudriavtseva

2021-03-05 15:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-07 12:35 UTC, SinimaWath requested changes

2021-03-07 12:35 UTC, SinimaWath commented on 1-module/1-task/index.js
> +        result *= n--;
Разбирали такую запись на лекции.

ЕЕ очень сложно понимать. Нужна разделить эту операцию на 2 части:
```
result *= n;
n--
```

2021-03-07 12:35 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
1. У тебя падает тесты: проверь локально `npm test`
2. Должно быть includes(' ');
3. Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return name != null ....`, давай так и сделаем

2021-03-07 12:35 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return str[0].toUpperCase() + str.slice(1);
В JS предпочитльней:
```
if (!str) {
 ...
}
```

2021-03-07 12:35 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
Это const, так как неизменяется

2021-03-08 19:39 UTC, SinimaWath approved these changes

2021-03-08 19:40 UTC, merged