Решение 2-module
js-tasks-ru/jsbasic-20210225_natalya72 pull request #4
Opened 2021-03-12 13:08 UTC by nataliaKudriavtseva

Не проходят два теста. 
1. в первом модуле второй задачи, но мне смержили
2. во втором модуле первой задачи

2021-03-12 13:08 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-12 15:21 UTC, SinimaWath requested changes
Давай еще поправим 2 задачу первого модуля. 

Я там и правда, случайно не заметил ошибку

2021-03-12 15:21 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (typeof salaries[key] !== NaN || typeof salaries[key] !== Infinity || typeof salaries[key] !== -Infinity) {
`typeof NaN` это `number`
`typeof Infinity ` это `number`
`typeof -Infinity ` это `number`

2021-03-12 15:21 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (typeof salaries[key] !== NaN || typeof salaries[key] !== Infinity || typeof salaries[key] !== -Infinity) {
Так что такое решение не будет работать. 

Попробуй поискать специальный метод, для определения этих 3-ех случаев

2021-03-12 15:21 UTC, SinimaWath commented on 2-module/3-task/index.js
> +
Маленькая рекомендация. Лучше в обьектах, заранее инициализировать, свойства которые будут использоваться.
```
let calculator = {
  firstOperand: null,
  secondOperand: null,
  
  read(..) ...
}
```

Зачем?
Разработчик, который будет читать этот код, сможет сразу понять, что в обьекте есть такие поля: `firstOperand `, `secondOperand `.

2021-03-13 14:08 UTC, nataliaKudriavtseva commented
Исправила. 
Но в первом модуле второй задачи я писала, что не понимаю, что написать, чтобы прошел тест. "если имя корректное, то true"

2021-03-14 17:25 UTC, SinimaWath requested changes
В 1 модуле, должно быть условие: `name.length >= 4`

2021-03-14 17:25 UTC, SinimaWath commented on 2-module/3-task/index.js
> +
Поправь это тоже замечание

2021-03-14 20:26 UTC, SinimaWath requested changes

2021-03-14 20:26 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return a;
Тут лишняя промежуточная переменная

2021-03-14 20:26 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return a;
Также используй тут деструкторизацию для аргументов функции, которые показывал на лекции

2021-03-14 20:26 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return arr.filter(item => (a <= item && item <= b));
Тут лишние скобки в стрелочной функции: `item => a <= item ...`

2021-03-15 13:45 UTC, SinimaWath approved these changes

2021-03-15 13:45 UTC, merged